#spring.application.name=wsfenix
server.servlet.context-path=/wsfenix/api/v1
server.port=9000

#Neon
#spring.datasource.url=jdbc:postgresql://ep-lucky-morning-ayftg154-pooler.c-5.us-east-2.aws.neon.tech/db_sga?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_4iYfMCok2GVl

#Neon
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.datasource.initialize=true
#spring.datasource.schema=classpath:/schema.sql
#spring.sql.init.schema-locations=classpath:/schema.sql
#spring.datasource.continue-on-error=true
spring.sql.init.continue-on-error=true
spring.main.web-application-type=servlet

#JPA config
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
