#spring.application.name=wsfenix
server.servlet.context-path=/wsfenix/api/v1
#server.port=9000
server.port=${PORT:8080}

#LocalHost
#spring.datasource.url=jdbc:postgresql://localhost:5432/DB_SGA
#spring.datasource.username=postgres
#spring.datasource.password=1234

#Neon
#spring.datasource.url=jdbc:postgresql://ep-lucky-morning-ayftg154-pooler.c-5.us-east-2.aws.neon.tech/db_sga?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_4iYfMCok2GVl

#Neon
#spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=5

#spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.datasource.initialize=true
#spring.datasource.schema=classpath:/schema.sql
#spring.sql.init.schema-locations=classpath:/schema.sql
#spring.datasource.continue-on-error=true
spring.sql.init.continue-on-error=true
spring.main.web-application-type=servlet

#JPA config
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
